![img.png](./data/img.png)

## PRACTICA OBLIGATORIA: **Transformación y Limpieza**

* La práctica obligatoria de esta unidad consiste en cargar un dataset de Netflix y hacer un repaso completo del mismo, limpiando, transformando y creando algunas variables. Descarga este notebook en tu ordenador y trabaja en local. Ten en cuenta que tendrás que descar los directorios de imágenes y datos adicionales, si los hubiera.
* Recuerda que debes subirla a tu repositorio personal antes de la sesión en vivo para que puntúe adecuadamente.  
* Recuerda también que no es necesario que esté perfecta, sólo es necesario que se vea el esfuerzo. 
* Esta práctica se resolverá en la sesión en vivo correspondiente y la solución se publicará en el repo del curso.

## #0 Carga de datos y primera exploración

In [1]:
import numpy as np
import pandas as pd

df_peliculas = pd.read_csv("data/dataset_netflix_titles.csv")

1. Haz una primera exploración de los datos. Haz una primera visualización de la tabla, muestra la información general, la descripción de las variables numéricas, las columnas y muestra la distribución de datos de tres columnas escogidas por ti.

In [5]:
print("Visualización tabla:\n")
df_peliculas

Visualización tabla:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [6]:
print("Vistazo general:\n")
df_peliculas.info()

Vistazo general:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [7]:
print("Descripción variables numéricas:\n")
df_peliculas.describe()

Descripción variables numéricas:

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [8]:
print("Muestra columnas:\n")
df_peliculas.columns

Muestra columnas:

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [11]:
print("Distribución 3 columnas:\n")
df_peliculas[["title","cast","release_year"]]

Distribución 3 columnas:

,title,cast,release_year
0,Dick Johnson Is Dead,NaN,2020
1,Blood & Water,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",2021
2,Ganglands,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",2021
3,Jailbirds New Orleans,NaN,2021
4,Kota Factory,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",2021
...,...,...,...
8802,Zodiac,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",2007
8803,Zombie Dumb,NaN,2018
8804,Zombieland,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",2009
8805,Zoom,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",2006
8806,Zubaan,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",2015

In [ ]:
print("Distribución title:\n",df_peliculas["title"].value_counts())
print("\nDistribución cast:\n",df_peliculas_peliculas_peliculas_peliculas_peliculas["cast"].value_counts())
print("\nDistribución release_year:\n",df_peliculas_peliculas_peliculas_peliculas_peliculas_peliculas_peliculas_peliculas_peliculas_peliculas["release_year"].value_counts())

Distribución title:
 title
Dick Johnson Is Dead     1
Blood & Water            1
Ganglands                1
Jailbirds New Orleans    1
Kota Factory             1
                        ..
Zodiac                   1
Zombie Dumb              1
Zombieland               1
Zoom                     1
Zubaan                   1
Name: count, Length: 8807, dtype: int64

Distribución cast:
 cast
David Attenborough                                                                                                                                             19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                                                        14
Samuel West                                                                                                                                                    10
Jeff Dunham                                                                                                                                                     7
Michela Luci, Jamie Watson, Eric Peterson, Anna Claire Bartlam, Nicolas Aqui, Cory Doran, Julie Lemieux, Derek McGrath                                          6
                                                                                                                                                               ..
Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, Mansoor Alfeeli, Ahd                                                                                              1
Mark Ruffalo, Jake Gyllenhaal, Robert Downey Jr., Anthony Edwards, Brian Cox, Elias Koteas, Donal Logue, John Carroll Lynch, Dermot Mulroney, Chloë Sevigny     1
Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf                                                             1
Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers                                         1
Logan Browning, Brandon P. Bell, DeRon Horton, Antoinette Robertson, John Patrick Amedori, Ashley Blaine Featherson, Marque Richardson, Giancarlo Esposito      1
Name: count, Length: 7692, dtype: int64

Distribución release_year:
 release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1961       1
1925       1
1959       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64

## #1 Duplicados y cardinalidad

1. ¿Existen filas duplicadas?¿Cuántas?

In [ ]:
df_peliculas.duplicated().sum()

np.int64(0)

In [ ]:
# CORRECCIÓN
subset_duplicados = df_peliculas.columns[(df_peliculas.nunique() / len(df_peliculas) * 100) != 100].to_list()
subset_duplicados

2. Deshazte de las filas duplicadas, si las hubiera. Quédate con las últimas copias.

In [ ]:
# No existen duplicados

# CORRECCIÓN
df_peliculas = df_peliculas.drop_duplicates(subset= subset_duplicados, keep="last")
df_peliculas

['type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [64]:
df_peliculas[subset_duplicados].duplicated().sum()

np.int64(1)

3. Ahora que no hay duplicados, tiene sentido calcular la cardinalidad de cada columna. Haz un programa que la obtenga y guarde el resultado en un diccionario con claves el nombre de las columnas y valores la cardinalidad (tal y como la hemos visto en el workout) de cada columna. [Nota: ¿has tenido en cuenta los valores nulos?]

In [22]:
cardinalidad_columnas = {}

for column in df_peliculas:
    cardinalidad = df_peliculas[column].nunique()/len(df_peliculas) * 100
    cardinalidad_columnas[column] = round(cardinalidad,2)

print("La cardinalidad de las columnas del DF es:\n",cardinalidad_columnas)

La cardinalidad de las columnas del DF es:
 {'show_id': 100.0, 'type': 0.06, 'title': 100.0, 'director': 51.41, 'cast': 87.34, 'country': 8.49, 'date_added': 20.06, 'release_year': 0.84, 'rating': 0.19, 'duration': 2.5, 'listed_in': 5.84, 'description': 99.64}

4. Haz un pequeño programa que recorra el diccionario y nos diga si hay alguna columna que pueda ser un buen índice (cardinalidad = 100%)

In [24]:
for column,cardinalidad in cardinalidad_columnas.items():
    if cardinalidad == 100:
        print(f"La columna {column} tiene buena cardinalidad {cardinalidad}")

La columna show_id tiene buena cardinalidad 100.0
La columna title tiene buena cardinalidad 100.0

Bonus: Haz los ejercicios 3 y 4 pero usando un objeto `Series` en vez de un diccionario.

In [34]:
serie_cardinalidad_columnas = pd.Series(cardinalidad_columnas.values(),
                                        index=cardinalidad_columnas.keys())
print(serie_cardinalidad_columnas)

for i,cardinalidad in enumerate(serie_cardinalidad_columnas):
    indice_columna = serie_cardinalidad_columnas.index[i]
    if cardinalidad == 100:
        print(f"Para {indice_columna} la cardinalidad es: {cardinalidad}, por lo que sería buen índice")

show_id         100.00
type              0.06
title           100.00
director         51.41
cast             87.34
country           8.49
date_added       20.06
release_year      0.84
rating            0.19
duration          2.50
listed_in         5.84
description      99.64
dtype: float64
Para show_id la cardinalidad es: 100.0, por lo que sería buen índice
Para title la cardinalidad es: 100.0, por lo que sería buen índice

## #2 Limpieza y transformación (I)

El primer paso en la limpieza es intentar detectar que campos están "sucios", una posible guía podría ser, encontrar:  
* Campos numéricos inconsistentes (el típico campo con la coma y el punto decimal mezclado, o con formatos numéricos combinados)  
* Campos con valores inconsistentes (por ejemplo aparecen valores que no tienen relación con la columna en la que están porque están mal colocados, porque se han incluido por error, valores medidos en una unidad frente a otros medidos en otra)  
* Campos con valores que son iguales pero están representados de formas diferentes (por ejemplo un actor que unas veces aparece con el nombre en un orden y otras veces con el nombre en otro, o el nombre de un país como USA que aparezca como EEUU otras veces, o cadenas que tienen espacios al principio y al final y Python las considera diferentes: " Clint Eastwood " y "Clint Eastwood").

Vamos a hacer un pequeño análisis siguiendo las pautas anteriores pero sin profundizar en ellas, en tu EDA sí que tendrás que hacerlo. Para ello nos vamos a centrar en los campos con cardinalidad menor que un 10% (el resto requiere un análsis mucho más exahustivo que se nos va fuera del alcance de la práctica, pero, repito en tu EDA tendrás que hacerlo)

1. Antes de centrarnos en esos campos, quita los espacios en blanco que pueda haber antes o después de cada valor string. (utiliza el método de cadenas de pandas, `strip`). Por ejemplo (como guía pero no como única solución) recorre con un for el nombre de las columnas y ve aplicando el método columna a columna. Pero puedes hacerlo como tú quieras, claro.

In [ ]:
df_peliculas.title.str.strip()

for columna in df_peliculas.columns:
    if df_peliculas[columna].dtype != int:
        df_peliculas[columna] =df_peliculas[columna].str.strip()
df_peliculas

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

Bonus: ¿Se te ocurre alguna forma rápida, que no necesariamente completa, de ver si ha afectado en algo esta operación?

2. Lista los campos con cardinalidad menor a 10%

In [44]:
columnas_baja_cardinalidad = []
for i,cardinalidad in enumerate(serie_cardinalidad_columnas):
    indice_columna = serie_cardinalidad_columnas.index[i]
    if cardinalidad < 10:
        columnas_baja_cardinalidad.append(indice_columna)
print("Columnas con cardinalidad menor que 10%:\n",columnas_baja_cardinalidad)

Columnas con cardinalidad menor que 10%:
 ['type', 'country', 'release_year', 'rating', 'duration', 'listed_in']

3. Para los campos que hayas obtenido, muestra su distribución de valores, sus valores únicos y determina si crees que se puede o debe hacer alguna acción de limpieza o transformación directa. No le des muchas vueltas.

In [48]:
for column in columnas_baja_cardinalidad:
    print(df_peliculas[column].value_counts())

type
Movie        5597
TV Show      1231
Series TV    1004
Film          534
Show          441
Name: count, dtype: int64
country
United States                                    2818
India                                             972
United Kingdom                                    419
Japan                                             245
South Korea                                       199
                                                 ...
Russia, Spain                                       1
Croatia, Slovenia, Serbia, Montenegro               1
Japan, Canada                                       1
United States, France, South Korea, Indonesia       1
United Arab Emirates, Jordan                        1
Name: count, Length: 748, dtype: int64
release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1961       1
1925       1
1959       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64
duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
97 min        146
             ...
228 min         1
18 min          1
205 min         1
201 min         1
191 min         1
Name: count, Length: 220, dtype: int64
listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
                                                   ...
Action & Adventure, Cult Movies                       1
Action & Adventure, Comedies, Music & Musicals        1
Classic Movies, Horror Movies, Thrillers              1
Children & Family Movies, Classic Movies, Dramas      1
Cult Movies, Dramas, Thrillers                        1
Name: count, Length: 514, dtype: int64

4. Limpia o simplifica/transforma dos de los campos detectados en 3, si hay al menos dos, si no, uno. Para ello puedes:  
4.1 Cualquier agrupa los valores de los campos tipo categoría con categorías similares que se llamen distinto.  
4.2 Quita valores extraños o que no correspondan. Conviertelos a "", y luego busca un valor para sustituirlos.

In [65]:
df_peliculas[df_peliculas.rating.str.contains("min", case=False, na=False)]
df_peliculas.loc[df_peliculas.rating.str.contains("min", case=False, na=False), "duration"] = df_peliculas.loc[df_peliculas.rating.str.contains("min", case=False, na=False), "rating"]
df_peliculas.loc[df_peliculas.rating.str.contains("min", case=False, na=False), "rating"] = np.nan

5. Convierte o cambia el tipo de la columna con fechas en strings a un tipo datetime. La columna que son solo años es mejor dejarla como integer, porque se opera muy fácil así. Tendrás que analizar los argumentos de pd.datetime y jugar con ellos para poder conseguirlo.

## #3 Tratamiento de Missings/Nulos

Es hora de tratar los nulos. Así que habrá que identificarlos para empezar.

1. Haz una lista con las columnas que contienen valores nulos. Obtenla a "mano" mirando la salid del método info o bien haz un programa que las obtenga de forma automática.

In [49]:
df_peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

2. Obten el porcentaje de valores nulos para cada una de las columnas.

In [56]:
porcentaje_null = round((df_peliculas.isna().sum()/len(df_peliculas)) *100,2)
porcentaje_null

show_id          0.00
type             0.00
title            0.00
director        29.91
cast             9.37
country          9.44
date_added       0.11
release_year     0.00
rating           0.05
duration         0.03
listed_in        0.00
description      0.00
dtype: float64

3. Corrige de la mejor manera que se te ocurra las dos columnas con menor porcentajes de nulos.

In [57]:
columnas_menor = ['rating', 'duration']
for columna in columnas_menor:
    df_peliculas[columna] = df_peliculas[columna].fillna(df_peliculas[columna].mode())

4. En un caso como este, que no hay apenas valores numéricos y las columnas con nulos no son categóricas, es mejor o deshacerse de los nulos o bien simplemente marcarlos pero convertidos a un valor más manejable y del tipo del resto de valores de la columna en la que aparecen. Por eso cambia los nulos en las columnas que no hayas tratado en el apartado anterior por "UNK" o por "".

In [58]:
columnas_restantes = ["director","cast","country","date_added"]
for columna in columnas_restantes:
    df_peliculas[columna] = df_peliculas[columna].fillna("")

5. Comprueba ahora que no hemos generado duplicados, si existiesen borralos y quedate la primera ocurrencia.

In [59]:
df_peliculas.duplicated().sum()

np.int64(0)

## #4 Generación de nuevos datos

Para terminar de hacer nuestro procesado, intentemos enriquecer el dataset y obtener alguna información adicional.

1. Separa el dataset en dos dataframes,uno de películas y otro de series. A veces aunque los datos parecen de la misma naturaleza, puede ser bueno separarlos para trabajar con ellos de forma independiente.

In [60]:
df_movies = df_peliculas[df_peliculas['type'] == 'Movie'].copy()
df_series = df_peliculas[df_peliculas['type'] == 'TV Show'].copy()

2. Ahora además podemos sacarle más provecho a algunos campos, por ejemplo duration. Muestra la distribución de valores para cada dataframe del campo "duration".

In [61]:
print(df_movies["duration"].value_counts())
print(df_series.duration.value_counts())

duration
90 min     134
97 min     133
91 min     132
94 min     130
93 min     128
          ...
178 min      1
228 min      1
18 min       1
201 min      1
191 min      1
Name: count, Length: 201, dtype: int64
duration
1 Season      833
2 Seasons     186
3 Seasons      98
4 Seasons      50
5 Seasons      26
6 Seasons      11
8 Seasons       9
7 Seasons       9
9 Seasons       4
10 Seasons      2
15 Seasons      1
11 Seasons      1
13 Seasons      1
Name: count, dtype: int64

3. Convierte los valores de "duration" en cada dataframe a valores numéricos y cambia en el de las series el nombre por uno más representativo. Se valorará el emplear una expresión regular para obtener la información.

4. BONUS: Crea un campo "Posible_Secuela" en el dataset de películas con valor a False por defecto. Intenta (con expresiones regulares si es posible) hacer una función que aplicada (con apply) a un título determine si es una posible secuela o no. Emplea la función (con apply) para rellenar el campo "Posible_Secuela". Nota: No hace falta que sea infalible,ni que las cace todas sino que tenga una lógica defendible, piensa en la forma que normalmente tienen las secuelas, por ejemplo la de Terminator.m..